### PR TITLE
Added DB_PORT to vars template

### LINKED ISSUE #59: Fresh install on unRAID never connects to database
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior

1. Install lychee 'app' from the community applications store.
2. Fill out the required template with db credentials etc.
3. Start container.
4. Access web UI

## Current Behavior
Container starts but connections to the web UI are refused indefinitely.
Viewing the log shows it spinning on "Waiting for database connection..."

## Steps to Reproduce
1. Remove any existing lychee appdata folder. (it doesn't hang if the config already exists).
2. Install lychee 'app'
3. Start container.
4. Try to connect to webUI (refused).
5. Check log.

## Environment
**OS:** unRAID 6.11.1
**CPU architecture:** x86_64
**How docker service was installed:**
NAS OS provided.

## Command used to create docker container (run/create/compose/screenshot)
image

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...........................................................................................................................+++++
..+++++
writing new private key to '/config/keys/cert.key'
-----
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/40-config
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
Waiting for database connection...
```

### PR DESCRIPTION
**Pull request by technofreak74**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-lychee/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Since this check was added to the startup script:
```
        until nc -z -v -w30 "${DB_HOST}" "${DB_PORT}"
        do
            echo "Waiting for database connection..."
            # wait for 5 seconds before check again
            sleep 5
        done
```
DB_PORT is no longer optional. I've added it to the readme_vars so that the correct [unraid template](https://github.com/linuxserver/templates/blob/main/unraid/lychee.xml) will get generated (and the readme is updated of course :smile:). I spent far too long trying to fix my database! :laughing:.

## Benefits of this PR and context:

Closes #59 ?

## How Has This Been Tested?
I ran the jenkins-builder and the changes to README.md look good?

I don't know how to prove that the unraid template is fixed..

### CODE REVIEW

**Comment by technofreak74** [comment]
I found the unRAID template in the .jenkins-external folder (after running the generator). It looks sensible although I haven't yet found a way to actually run it on my unRAID server.

The one other thing it did do was change the icon from:
`https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lychee-logo.png`
to
`https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png`
 
I'm assuming that is due to a change in the lsio unraid template generator?

**Comment by technofreak74** [comment]
If you do merge this please could you add the hacktoberfest-accepted label?

**Comment by technofreak74** [comment]
The Dockerfile builds fine against v4.4.0 of lychee but it looks like Jenkins is pulling in the latest (4.6.1). Is there any way to fix the version so it doesn't try to build against the latest? Or do I need to get it to build with 4.6.1? (probably out of reach for me...).

**Comment by aptalca** [comment]
Thanks for the PR. I added the hacktoberfest label to the repo.

The build fixes for the latest version are in #51 
Perhaps you should rebase this PR on that branch so we can merge both at once

**Comment by technofreak74** [comment]
Cool, thank you :smile: 

Hopefully this is what you meant.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
