### PR TITLE
Allowing video uploads of 500MB seems reasonable nowadays, rather than 20MB.

### PR DESCRIPTION
**Pull request by ZarTek-Creole**
Dear Maintainers,

I am writing to submit a pull request to increase the video upload limit from 20MB to 500MB for Lychee, which I am using as a Docker container from linuxserver.io. The current limit is insufficient for uploading larger video files, and I believe that raising the limit to 500MB would greatly benefit the userbase.

Here are the details of my pull request:

Description:
I propose increasing the video upload limit in the Lychee Docker container from 20MB to 500MB. This change will provide users with the ability to upload larger video files, accommodating their needs in today's multimedia-rich environment.

Benefits of this PR and context:
By raising the upload limit to 500MB, users will have greater flexibility and convenience when uploading videos to Lychee. It will enhance the overall user experience and enable them to seamlessly share high-quality video content.

How Has This Been Tested?
I have thoroughly tested this modification in my own testing environment. I have successfully uploaded various video files exceeding 20MB in size, up to 500MB, and verified that the upload process functions correctly without any issues.

Source / References:
No specific source or references are relevant to this pull request.

I have read and understood the contributing guidelines provided [here](https://github.com/linuxserver/docker-lychee/blob/master/.github/CONTRIBUTING.md) and ensured that my modifications align with them.

Thank you for considering my pull request. I believe that increasing the video upload limit will greatly improve the functionality of Lychee and benefit its userbase.

Sincerely,
[ZarTek-Creole](https://github.com/ZarTek-Creole)

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR, but that file is in the config folder and is user customizable. No need to change the defaults here.

**Comment by ZarTek-Creole** [comment]
> Thanks for the PR, but that file is in the config folder and is user customizable. No need to change the defaults here.

I would like to express my disagreement with the previous response regarding my request to modify the video upload limit in the Lychee Docker container provided by linuxserver.io. While I understand that the file in question is customizable by the user in the configuration folder, I believe that this information would be useful to include in the documentation. Furthermore, I found myself considering modifying the php.ini file, adjusting the Nginx configuration, or attempting to use a .htaccess file to adjust this limit.

Additionally, I would like to draw your attention to the following line in the default configuration file for Lychee: [root/defaults/user.ini#L7](https://github.com/linuxserver/docker-lychee/blob/1bb561ce5bc9cb51c19cd3118b12089359ece9a1/root/defaults/user.ini#L7). This line indicates that the default value for upload_max_filesize is set to 20M, while post_max_size and upload_max_size are set to 200. I am wondering if it would be possible to at least increase the value of upload_max_filesize to 200M. If not, it would be helpful to mention in the Docker documentation or in the FAQ that this limit can be easily modified by editing the respective file.

I want to emphasize that increasing the video upload limit would allow Lychee users to work more effectively with larger video files, meeting the current needs for multimedia content management. This enhancement would greatly contribute to the user experience

**Comment by aptalca** [comment]
I understand your position, however, `user.ini` is upstream's settings file and we use the defaults from the upstream project: <https://github.com/LycheeOrg/Lychee/blob/master/public/.user.ini>

You may think 500MB is a good default, others may disagree and suggest something higher or lower. There is no right answer. We go by the upstream project's defaults. Since it's user configurable, it's not a big deal. Every user can set it to whatever they like.

If you want to add a sentence to the readme about that file, feel free to submit a PR.

**Comment by ZarTek-Creole** [comment]
Closing this pull request as the issue raised has been addressed in a different manner with pull request https://github.com/linuxserver/docker-lychee/pull/65.

In that pull request, we've updated the README.md to provide detailed instructions for users to customize upload limits as per their needs. This approach allows users to have flexibility based on their specific requirements and server capacity, rather than changing the defaults for everyone.

I hope my contribution is useful and appreciated. Thank you for your time and consideration.

Best regards,
[ZarTek-Creole](https://github.com/ZarTek-Creole)

**Pull request closed without merging**
