### PR TITLE
Standard base

### PR DESCRIPTION
**Pull request by nemchik**
Ref: https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/84

### CODE REVIEW

**Comment by nemchik** [comment]
Screenshot looks strange. It should be showing the app, not the default index.

edit: it was cached, it's fine now

**Comment by nemchik** [comment]
@technofreak74 can you test `lspipepr/lychee:v4.6.1-pkg-61a4e78d-pr-51` ?

**Comment by technofreak74** [comment]
I don't know how to test the unraid template but running `lspipepr/lychee:v4.6.1-pkg-61a4e78d-pr-51` via docker compose (on a fresh ubuntu VM) works? I've only just started using lychee though so I'm not sure how conclusive my 'works' is :smile:

**Comment by TechGeeksIO** [comment]
I've tested `lspipepr/lychee:v4.6.1-pkg-61a4e78d-pr-51 `and it seems to work fine if you install a fresh container, if I try to upgrade my old container with the current version (master branch) I get the following error message:

grafik


Edit: sounds like I have the same issue like him and this is related to my nginx reverse proxy
https://github.com/LycheeOrg/Lychee-Docker/issues/133

**Comment by thespad** [comment]
> I've tested `lspipepr/lychee:v4.6.1-pkg-61a4e78d-pr-51 `and it seems to work fine if you install a fresh container, if I try to upgrade my old container with the current version (master branch) I get the following error message:
> 
> grafik
> 
> Edit: sounds like I have the same issue like him and this is related to my nginx reverse proxy [LycheeOrg/Lychee-Docker#133](https://github.com/LycheeOrg/Lychee-Docker/issues/133)

Check your container logs with the upgrade and see what it mentions about outdated confs - you probably just need to remove the old ones and let them get re-copied.

**Comment by anthonyrussano** [comment]
I have setup a clean install and an upgrade environment to test.

Everything seems to work fine in both enviroments, except for the sharing button.
When I click the share button for an individual photo, nothing happens.
I will try to perform some additional debugging.

**Comment by anthonyrussano** [comment]
I think this share button issue might be related to the BadRequestHeaderException

https://github.com/LycheeOrg/Lychee-Docker/issues/133

image

**Review by thespad — APPROVED** [review]

**Pull request merged**
